CREATE DATABASE estudantesdb;

\c estudantesdb;

CREATE TABLE avaliacao (
    id SERIAL PRIMARY KEY,
    nota INTEGER NOT NULL,
    professor VARCHAR(255) NOT NULL
);

CREATE TABLE estudante (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    numero_registro INTEGER NOT NULL,
    photo TEXT,
    avaliacao_id INTEGER REFERENCES avaliacao(id) ON DELETE CASCADE
);

INSERT INTO avaliacao (nota, professor) VALUES
(8, 'Thomas Shelby'),
(7, 'Arthur Shelby'),
(9, 'Polly Gray'),
(6, 'John Shelby'),
(10, 'Ada Shelby'),
(5, 'Michael Gray'),
(8, 'Finn Shelby'),
(7, 'Alfie Solomons'),
(6, 'Chester Campbell'),
(9, 'Grace Burgess'),
(10, 'Luca Changretta'),
(4, 'Oswald Mosley'),
(7, 'Aberama Gold'),
(6, 'Lizzie Stark'),
(5, 'Johnny Dogs'),
(8, 'Jeremiah Jesus'),
(9, 'Esme Shelby'),
(7, 'Billy Kimber'),
(6, 'Curly'),
(5, 'Freddie Thorne'),
(10, 'Major Campbell'),
(4, 'Tatiana Petrovna'),
(7, 'Jessie Eden'),
(8, 'Linda Shelby'),
(9, 'Barney Thompson'),
(6, 'Jimmy McCavern'),
(5, 'Captain Swing'),
(7, 'Duke Shelby'),
(8, 'Hayden Stagg'),
(6, 'Charles Shelby'),
(9, 'Mickey Gibbs'),
(10, 'Isiah Jesus'),
(4, 'Clive Arthur'),
(5, 'Earl of Compton'),
(6, 'Henry Russell'),
(7, 'Georgie Wilson'),
(8, 'Karl Thorne'),
(5, 'Martha Shelby'),
(9, 'Katie Eden'),
(6, 'Nancy Gray'),
(10, 'Diana Mitford'),
(4, 'Rowena Gold'),
(8, 'Patrick Jarvis'),
(7, 'Ada Thorne'),
(6, 'Tommys Secretary'),
(5, 'Mr. Levitt'),
(9, 'Doctor Holford'),
(10, 'Ruby Shelby'),
(4, 'Mr. Zhang'),
(6, 'Anton Kaledin'),
(8, 'Reverend James'),
(7, 'Sean Gibbons'),
(9, 'Connor Nutley'),
(6, 'Dougie Bill'),
(5, 'Gina Gray'),
(10, 'Mr. Cheng'),
(8, 'Billy Grade'),
(7, 'Harry Fenton'),
(6, 'Stephen Knight'),
(5, 'Mr. Costello'),
(9, 'Nancy Shelby'),
(10, 'Evan Gillen'),
(4, 'Father Hughes'),
(7, 'Mr. Devlin'),
(8, 'Mr. Brody'),
(6, 'Malacki Byrne'),
(5, 'Sean Byrne'),
(9, 'Tommys Driver'),
(10, 'Francis'),
(4, 'Maggie'),
(6, 'Thomas Senior'),
(7, 'Mrs. Ross'),
(8, 'Inspector Moss'),
(9, 'Detective Perkins'),
(5, 'Father Jeremiah'),
(6, 'Rory ODonnell'),
(7, 'Captain Fraser'),
(8, 'Danny Whizz-Bang'),
(9, 'Patrick Shelby'),
(10, 'Sean Shelby'),
(4, 'Louisa Gold'),
(5, 'Megan Gray'),
(6, 'Mr. Harvey'),
(7, 'Agent Wilson'),
(8, 'Inspector Campbell'),
(9, 'Mick Fitzgerald'),
(10, 'Mrs. Devlin'),
(5, 'Ciaran Gold'),
(6, 'Peter Browne'),
(7, 'David Byrne'),
(8, 'Ellie Eden'),
(9, 'Oliver Shelby'),
(10, 'Mrs. Abernathy'),
(4, 'Father McGee'),
(6, 'Sam Neill'),
(7, 'Tom Hardy'),
(8, 'Helen McCrory'),
(9, 'Paul Anderson'),
(10, 'Anya Taylor-Joy'),
(11, 'Paul Anderson'),
(12, 'Anya Taylor-Joy');



INSERT INTO estudante (name, numero_registro, photo, avaliacao_id) VALUES
('Jack', 1, '/images/jack.png', 1),
('Kate', 2, NULL, 2),
('Sawyer', 3, NULL, 3),
('Locke', 4, NULL, 4),
('Hurley', 5, NULL, 5),
('Sayid', 6, NULL, 6),
('Charlie', 7, NULL, 7),
('Claire', 8, NULL, 8),
('Jin', 9, NULL, 9),
('Sun', 10, NULL, 10),
('Desmond', 11, NULL, 11),
('Juliet', 12, NULL, 12),
('Ben', 13, NULL, 13),
('Michael', 14, NULL, 14),
('Walt', 15, NULL, 15),
('Shannon', 16, NULL, 16),
('Boone', 17, NULL, 17),
('Ana Lucia', 18, NULL, 18),
('Libby', 19, NULL, 19),
('Mr. Eko', 20, NULL, 20),
('Daniel', 21, NULL, 21),
('Charlotte', 22, NULL, 22),
('Miles', 23, NULL, 23),
('Frank', 24, NULL, 24),
('Rose', 25, NULL, 25),
('Bernard', 26, NULL, 26),
('Ethan', 27, NULL, 27),
('Richard', 28, NULL, 28),
('Alex', 29, NULL, 29),
('Karl', 30, NULL, 30),
('Pierre', 31, NULL, 31),
('Widmore', 32, NULL, 32),
('Penny', 33, NULL, 33),
('Ellie', 34, NULL, 34),
('Zoe', 35, NULL, 35),
('Nikki', 36, NULL, 36),
('Paulo', 37, NULL, 37),
('Jacob', 38, NULL, 38),
('Man in Black', 39, NULL, 39),
('Vincent', 40, NULL, 40),
('Jack', 41, NULL, 41),
('Kate', 42, NULL, 42),
('Sawyer', 43, NULL, 43),
('Locke', 44, NULL, 44),
('Hurley', 45, NULL, 45),
('Sayid', 46, NULL, 46),
('Charlie', 47, NULL, 47),
('Claire', 48, NULL, 48),
('Jin', 49, NULL, 49),
('Sun', 50, NULL, 50),
('Desmond', 51, NULL, 51),
('Juliet', 52, NULL, 52),
('Ben', 53, NULL, 53),
('Michael', 54, NULL, 54),
('Walt', 55, NULL, 55),
('Shannon', 56, NULL, 56),
('Boone', 57, NULL, 57),
('Ana Lucia', 58, NULL, 58),
('Libby', 59, NULL, 59),
('Mr. Eko', 60, NULL, 60),
('Daniel', 61, NULL, 61),
('Charlotte', 62, NULL, 62),
('Miles', 63, NULL, 63),
('Frank', 64, NULL, 64),
('Rose', 65, NULL, 65),
('Bernard', 66, NULL, 66),
('Ethan', 67, NULL, 67),
('Richard', 68, NULL, 68),
('Alex', 69, NULL, 69),
('Karl', 70, NULL, 70),
('Pierre', 71, NULL, 71),
('Widmore', 72, NULL, 72),
('Penny', 73, NULL, 73),
('Ellie', 74, NULL, 74),
('Zoe', 75, NULL, 75),
('Nikki', 76, NULL, 76),
('Paulo', 77, NULL, 77),
('Jacob', 78, NULL, 78),
('Man in Black', 79, NULL, 79),
('Vincent', 80, NULL, 80),
('Jack', 81, NULL, 81),
('Kate', 82, NULL, 82),
('Sawyer', 83, NULL, 83),
('Locke', 84, NULL, 84),
('Hurley', 85, NULL, 85),
('Sayid', 86, NULL, 86),
('Charlie', 87, NULL, 87),
('Claire', 88, NULL, 88),
('Jin', 89, NULL, 89),
('Sun', 90, NULL, 90),
('Desmond', 91, NULL, 91),
('Juliet', 92, NULL, 92),
('Ben', 93, NULL, 93),
('Michael', 94, NULL, 94),
('Walt', 95, NULL, 95),
('Shannon', 96, NULL, 96),
('Boone', 97, NULL, 97),
('Ana Lucia', 98, NULL, 98),
('Libby', 99, NULL, 99),
('Mr. Eko', 100, NULL, 100);